name: Snyk CI/CD Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        run: snyk test --file=GitHub/package.json --package-manager=npm
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Monitor
        run: snyk monitor --file=GitHub/package.json --package-manager=npm
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
